CREATE TABLE login (
    permanentId CHAR(36) NOT NULL,
    login VARCHAR(64) NOT NULL,
    cancelled BOOLEAN NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE email (
    permanentId CHAR(36) NOT NULL,
    email VARCHAR(128) NOT NULL,
    cancelled BOOLEAN NOT NULL,
    auth BOOLEAN NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE password (
    permanentId CHAR(36) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    cancelled BOOLEAN NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE temporaryId (
    permanentId CHAR(36) NOT NULL,
    temporaryId CHAR(36) NOT NULL,
    userAgent VARCHAR(255) NOT NULL,
    cancelled BOOLEAN NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE refresh_token (
    permanentId CHAR(36) NOT NULL,
    token VARCHAR(255) NOT NULL,
    userAgent VARCHAR(255) NOT NULL,
    cancelled BOOLEAN NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE reset_token (
    token VARCHAR(255) NOT NULL,
    permanentId CHAR(36) NOT NULL,
    cancelled BOOLEAN NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;