CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
);

CREATE TABLE tokens (
userID INT NOT NULL,
token VARCHAR(255) PRIMARY KEY,
expiresAt DATETIME NOT NULL,
deviceInfo VARCHAR(255)
FOREIGN KEY (userID) REFERENCES user(id)
);