name: auth
services:
  app:
    image: gimaevra94/app:latest
    container_name: app
    hostname: app
    environment:
       DB_PASSWORD_FILE: /run/secrets/db_password
       DB_USER: root
    ports:
      - 8000:8000
    profiles: 
      - dev
    networks:
      - net
    volumes:
      - /c/Users/gimaevra94/Documents/git/auth/app/web:/app/web
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_password

  db:
    image: gimaevra94/db:latest
    container_name: db
    hostname: db
    environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
       MYSQL_DATABASE: db
    volumes:
      - db:/db
    ports: 
      - 3306:3306
    profiles:
      - dev
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
    secrets:
      - db_password

volumes:
  db:

networks:
  net:
    driver: bridge

secrets:
  db_password:
    file: ./db_password.txt