package consts

import "time"

const (
	SelectQuery = "select password from users where email = ? limit 1"
	InsertQuery = "insert into users (email,login,password) values(?,?,?)"

	EmailRegex    = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?(\.[a-zA-Z]{2,})+$`
	LoginRegex    = `^[a-zA-Zа-яА-ЯёЁ0-9]{3,30}$`
	PasswordRegex = `^(?=.*[a-zA-Zа-яА-ЯёЁ])(?=.*\d)(?=.*[!@#$%^&*])[\w!@#$%^&*]{3,30}$`

	SignUpURL          = "/sign_up"
	InputCheckURL      = "/input_check"
	CodeSendURL        = "/code_send"
	UserAddURL         = "/user_add"
	SignInURL          = "/sign_in"
	LogInURL           = "/log_in"
	SendCodeAgain      = "/send_code_again"
	HomeURL            = "/home"
	LogoutURL          = "/log_out"
	LoginWithGoogleURL = "/login_with_google"

	SignUploginInput      = "signUploginInput.html"
	RequestErrorHTML      = "requestError.html"
	UserAllreadyExistHTML = "userAllreadyExist.html"
	CodeSendHTML          = "codeSend.html"
	WrongCodeHTML         = "wrongCode.html"
	SignInloginInputHTML  = "signInloginInput.html"
	UserNotExistHTML      = "userNotExist.html"
	HomeHTML              = "home.html"
	BadSignUp             = "badSign-up.html"
	BadSignIn             = "badSign-in.html"

	UserGetFromSessionErr        = "userGetFromSession failed"
	UserSetFromSessionErr        = "userSetFromSession failed"
	UserAllreadyExistErr         = "User allready exist"
	CookieGetFailedErr           = "Failed to get the key"
	KeyGetFailedErr              = "Failed to get the key"
	SessionSaveFailedErr         = "Failed to save the session"
	SessionGetFailedErr          = "Failed to get the session"
	CodesNotMatchErr             = "The userCode does not match the msCode"
	InputValidateFailedErr       = "Failed to validate the input"
	UserSerializeFailedErr       = "Failed to serialize the 'user'"
	UserDeserializeFailedErr     = "Failed to serialize the 'user'"
	UserSaveInSessionFailedErr   = "Failed to save the 'user' in the session"
	UserNotExistInSessionErr     = "'user' is not exist in the session"
	MscodeNotExistInSessionErr   = "'mscode' is not exist in the session"
	MailSendlerFailedErr         = "MailSendler failed: "
	ExpireGetFromClaimsFailedErr = "Failed to get the expire from the claims"
	ParseFromTokenFailedErr      = "Failed to parse from token"
	TokenGetFailedErr            = "Failed to get the token"
	ClaimsGetFailedErr           = "Failed to get the claims"
	TokenValidateFailedErr       = "Failed to validate the token"
	TokenCreateFailedErr         = "Failed to create the token"
	UserAddInDBFailedErr         = "Failed to add the 'user' in db"
	RememberGetInFormFailedErr   = "Failed to get the 'remember' from the FormValue"
	PasswordFileReadFailedErr    = "Failed to read 'db_password.txt'"
	MscodeSaveInSessionFailedErr = "Failed to save the mscode in the session"
	UserNotExistInDBErr          = "User not exist in db"
	PasswordHashingFailedErr     = "Failed to hash the password"
	SqlOpenFailedErr             = "sql.Open failed"
	DBStartFailedErr             = "Failed to start the database"
	DBPingFailedErr              = "DB.Ping failed"
	PasswordGetFromFormFailedErr = "Failed to get thr password from the FormValue"
	PasswordsNotMatchErr         = "inputPassword does not match passwordHash"
	AccessCodeSendFailedErr      = "Failed to send access code fron user email"
	SessionEndedErr              = "session ended"
	DBStartServerFailedErr       = "Failed to start the server"
	TokenSignFailedErr           = "Failed to sign the token"
	InvalidTokenErr              = "Token is invalid"
	EmailGetFromFormFailedErr    = "Failed to get email from the FormValue"
	EmptyValueErr                = "value is empty"
	ValidationFailedErr          = "validation failed"
	RegexKEyNotMatchErr          = "regex key not matching"
	DBQueryExecuteFailedErr      = "Failed to execute query against the db"
	LoginGetFromFormFailedErr    = "Failed to get login from the FormValue"
	DatGetFailed                 = "Failed to get the data from: "

	LoginStr              = "login"
	EmailStr              = "email"
	UserStr               = "user"
	MscodeStr             = "mscode"
	UserCodeStr           = "code"
	SessionNameStr        = "auth"
	RememberStr           = "remember"
	LastActivityStr       = "lastActivity"
	EmptyValueStr         = ""
	AuthCookieNameStr     = "Authorization"
	AuthCookiePath        = "/set-token"
	DBConfUserNameStr     = "root"
	DBConfNetNameStr      = "tcp"
	PasswordStr           = "password"
	DBConfAddrNameStr     = "db:3306"
	DBConfDBNameStr       = "db"
	DBPasswordPathStr     = "/run/secrets/db_password"
	DBNameDriverStr       = "mysql"
	TokenCommand3HoursStr = "expire_3_hours"
	ExpStr                = "exp"
	AccessCodeStr         = "Access code: "
	MailUserNameStr       = "gimaev.vending@ya.ru"
	SMTPHostStr           = "smtp.yandex.ru"
	SMTPAddrStr           = "smtp.yandex.ru:587"
	OnValueStr            = "on"
	BearerStr             = "Bearer"
	ServerPortStr         = ":8080"
	SlashStr              = "/"

	TokenLifetime3HoursInt = 3 * time.Hour
	ThousandStr            = 1000
)
