name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push DB image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: email_auth/Docker/Dockerfile.db
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ vars.DOCKER_USERNAME }}/db:latest

      - name: Build and push App image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: email_auth/Docker/Dockerfile.app
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ vars.DOCKER_USERNAME }}/app:latest

      - name: Build and push with Docker Compose
        run: |
          docker compose -f email_auth/Docker/docker-compose.yml build
          docker compose -f email_auth/Docker/docker-compose.yml push
